[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/andre/printer_data/comms/klippy.sock
[authorization]
trusted_clients:
    192.168.0.0/16
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FC00::/7
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz
[octoprint_compat]
[timelapse]
[history]
[file_manager]
enable_object_processing: True
[update_manager]
channel: dev
refresh_interval: 168
[update_manager mainsail]
path: /home/andre/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json
[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/andre/mainsail-config
primary_branch: master
type: git_repo
[update_manager fluidd]
path: /home/andre/fluidd
repo: fluidd-core/fluidd
channel: stable
type: web
persistent_files:
    config.json
[update_manager Klipper-Adaptive-Meshing-Purging]
type: git_repo
channel: dev
path: ~/Klipper-Adaptive-Meshing-Purging
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services: klipper
primary_branch: main
# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh
[update_manager KlipperScreen]
install_script: /home/andre/KlipperScreen/scripts/KlipperScreen-install.sh
requirements: /home/andre/KlipperScreen/scripts/KlipperScreen-requirements.txt
env: /home/andre/.KlipperScreen-env/bin/python
managed_services: KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
path: /home/andre/KlipperScreen
type: git_repo
# moonraker.conf
[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker
[update_manager mobileraker]
install_script: /home/andre/mobileraker_companion/scripts/install.sh
requirements: /home/andre/mobileraker_companion/scripts/mobileraker-requirements.txt
env: /home/andre/mobileraker-env/bin/python
managed_services: mobileraker
primary_branch: main
origin: https://github.com/Clon1998/mobileraker_companion.git
path: /home/andre/mobileraker_companion
type: git_repo
[include octoeverywhere-system.cfg]
[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main
[mqtt]
address: 127.0.0.1
port: 1883
[sensor chamber_env]
type: mqtt
name: Chamber Env

parameter_temperature:
  units=C
parameter_humidity:
  units=%
parameter_voc_index:
  units=PPCM

state_topic: printer/air_monitor/state
state_response_template:
  {% set d = payload|fromjson %}
  {set_result("temperature", d["temperature"]|float)}
  {set_result("humidity", d["humidity"]|float)}
  {set_result("voc_index", d["voc_index"]|float)}
[update_manager backup_pie]
type: git_repo
path: /home/andre/Backup-Pie
origin: https://github.com/AMOVFC/Tri-Zero
primary_branch: main
is_system_service: False
