; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2026-02-08 at 13:21:15
; total layer number: 1
; filament_density: 1.04
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 400
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA8klEQVR4Ae2YsQ3EIAxFGYCeDgo6KF
; jhRrvNMtqdXCCRKEEhgLEjP8lSlOrH/zsyKCUIgiAIE9Baf1JKP+/9Bs+KE8aYL4gvC94pDpyJz0Xa
; jZpw8m60iC/dUKt5IpxMpHrFL4sUdAw6N0o8qhsju47uBob4KQOOKfxY3ZFaKb4rUrMGtSdSt92g0P
; XHblAWX3WDg/Bj7T4i7+6c6jROlAa3SfhrhriMFNvfKDU3uncj+PIYI0/xJZiRYr2RTj/czBpway3u
; GZntkbJkhBsk7omccxubrl/Rsk+RvmasRYr1/Sgb8Zk84CEEGoMqCIIgvJI/xlKCP/cSQqEAAAAASU
; VORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 2424
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAG30lEQVR4Ae3dS44USRKA4TgAK4TEpg
; SLFBKCBVfoo3GzOhqtaFR0klX5iAh/mLl/n/RLo9lNa9rHzCaDXhYAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANL7+PHjz3fv3v2zAES2PlY/fvz4tb
; b+6wUgmnWiOp1Ozy+P1Uvrv2faAsI4n6quZdoCunvksTqfthaA1rY8VJdZEYFmjjxWVkSgiWuH9b05
; yANVlJiqTFtAdTUfK9MWUESLh8pBHjisx2NlRQQ26flQWRGBh0V5rExbwE0lf65g2gKqiDhVmbaAVz
; I9VufT1gLMI+NDdZkVESYwwmP1khURBlX6O8AoOcjDYEaaqkxbMLAZHqvzaWsB8pnpobrMigiJzPxY
; vWRFhODWySLTo1I7B3kIylR1PdMWBOKxup9pCzrzUG3PtAUdeKz25+cP0IiHqtyjZUWEijxW5bMiQm
; GjfgcYJdMWFGKqapdpCw7wWLXPQR428lD1z4oID/BYxcmKCFc4rMfMQR4umKriZ9qCxWOVKdMW0/JQ
; 5c2jxVQ8Vvl7enry8wfG5qEaKysiw/JYjZuDPEPxc4XxM22RnqlqvkxbpOSxmjffI5KGh0ovWREJzW
; Oly6yIhOM7QN3KQZ4wTFV6NNMWXXmstDUHeZrzUOloVkSa8FipVFZEqln/FzHT3wzKkYM8xZmqVDvT
; FkX4uYJaZdpiN1OVemXaYhOPlXrn5w/c5aFSpL5+/ernD7zNY6WoWRH5w3eAypCDPKYqpcu0NSmPlb
; LmID8RD5VGyYo4OI+VRsuKOCDfAWrkHOQHYqrSLJm2kvNYabZMWwl5qDR7Hq0kPFbS7/z8ITAPlfQ6
; K2JAHivpdg7yAfgOUHo801ZHpippX6atxjxW0rEc5BvwUEllsyJW4rGS6mRFLMhhXaqfg3wBpiqpba
; atnTxWUp9MWxt4qKQYebTu8FhJsbIivsFDJcXNinjGYyXlaPppy88VpFxNOW2ZqqTcTTNteaykMRr6
; e0QPlTRmw62IHitp7IZYEX0HKM1T6oO8qUqas3TTlsdKmrsUB3kPlaTzwq6IHitJbxVqRVxf0Ex/8S
; S1L8RB3lQlaUvdpi2PlaQ9NZ22PFSSSlR92vJYSSpZlZ8/eKgk1aroiuixktSiQyui7wAlte7QtPX5
; 8+fnTP9hJeXu06dPx25aHz58+Pn9+/dU/6El5avo/2toPZRUoy9fvvxaarAiSipZ9d9irQcxK6KkI1
; Wbqq4xbUnaU7fvCU1bkrYU4s/HMm1JulXzFfCe9ecPmf4CSmpT6D/j3YooaS3cVHWNFVGau3T/5BwH
; eWm+vn37lvufBG3akubo8HeAUTjIS2M3xD+q/pIVURqrNIf1vayI0hgNOVW9xUFeytt6WF9mZNqScj
; XMYX0vf0CglKNpVsBHmLakmA1/WN/Lzx+kWJmq7nCQl/pnqtrIiij1yVS1k2lLalf67wCjMG1JdZv+
; 5wqlOchLdbICVmRFlMrksN6IFVE6lqmqMQd5aXsO652ZtqTHclgPwveI0u2sgAGdTqfnTP8lkmrnsB
; 6cFVH6nakqCQd5zZypKinTlmbLVJWcaUuz5OcKAzFtadSsgIPyPaJGywo4ASuismeqmowVUVkzVU3K
; QV6Z8h0g/zFtKXq+A+QvDvKKmhWQq6yIipLDOg+xIqp3pio2cZBXj9bD+gJ7mbbUKod1ivAHBKp279
; +//7lASaYtlc5hnar8/EGlclinCQd5HclURRdWRG3NVEVXpi09ku8ACcW0pWv5uQIhOcjrMisg4VkR
; 5bBOKlbEeTNVkZKD/Fw5rDME09b4OawzFN8jjpsVkGGdTqfnTH8z6noO60zh6enpOdPfmHqdqYqpOM
; jnzFTF1Bzk82SqgsW0FT0/V4A3mLbi5ecKcIPvEeNkBYQHWRH75bAOO1gR22eqggMc5NvksA4Fmbbq
; 5bAOFfgesXxWQKjM94jHc1iHhqyI+zNVQQcO8ttaD+sL0Jdp636mKgjEtHU9P1eAoExb/+ewDgn4Ht
; EKCOnMuCKaqiCxmVZEUxUMYPSDvO8AYUAjTlu+A4SBjXSQtwLCJDKviA7rMKGMK6KpCiaW5SDvO0Dg
; j8jTlsM68ErEPyDQCgjcFGHaclgHHtbz5w+mKmCz1gd5UxVwWIsV0VQFFFNr2vIdIFBNyWnLzxWA6k
; oc5K2AQFN7VkSHdaCbLSuiqQro7t5B3mEdCOetacthHQjr/HtEKyAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADN/AtW7S7GPou4YgAAAABJRU5Erk
; Jggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

; EXECUTABLE_BLOCK_START


; Pre-Processed for Cancel-Object support by preprocess_cancellation v0.2.0
; 1 known objects
EXCLUDE_OBJECT_DEFINE NAME=z_offset_check_stl_id_15_copy_0 CENTER=60.000,60.000 POLYGON=[[10.35,10.35],[10.35,109.65],[109.65,109.65],[109.65,10.35]]
M73 P0 R2
;TYPE:Custom
PRINT_START EXTRUDER_TEMP=255 BED_TEMP=105
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
SET_PRESSURE_ADVANCE ADVANCE=0.04; Override pressure advance value
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-.8 F1800
;AFTER_LAYER_CHANGE
;0.2
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=10000 ACCEL_TO_DECEL=10000
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=9
; printing object z-offset-check.stl id:15 copy 0
EXCLUDE_OBJECT_START NAME=z_offset_check_stl_id_15_copy_0
G1 Z.6 F36000
G1 X109.65 Y109.65
G1 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Outer wall
;WIDTH:0.4
G1 F6000
G1 X10.35 Y109.65 E2.68299
G1 X10.35 Y10.35 E2.68299
M73 P1 R2
G1 X109.65 Y10.35 E2.68299
G1 X109.65 Y10.495 E.00392
M73 P2 R2
G1 X109.65 Y109.61 E2.67799
G1 E-.56 F1800
M73 P3 R2
;WIPE_START
G1 F6000
G1 X108.65 Y109.61 E-.24
;WIPE_END
G1 Z.6 F36000
G1 X109.543 Y10.618 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Bottom surface
;WIDTH:0.400759
G1 F12600
G1 X10.618 Y10.618 E2.67854
G1 X10.618 Y10.976 E.00969
G1 X109.382 Y10.976 E2.67419
G1 X109.382 Y11.334 E.00969
M73 P4 R2
G1 X10.618 Y11.334 E2.67419
G1 X10.618 Y11.692 E.00969
G1 X109.382 Y11.692 E2.67419
G1 X109.382 Y12.05 E.00969
G1 X10.618 Y12.05 E2.67419
G1 X10.618 Y12.407 E.00969
M73 P5 R2
G1 X109.382 Y12.407 E2.67419
G1 X109.382 Y12.765 E.00969
G1 X10.618 Y12.765 E2.67419
G1 X10.618 Y13.123 E.00969
G1 X109.382 Y13.123 E2.67419
G1 X109.382 Y13.481 E.00969
M73 P6 R2
G1 X10.618 Y13.481 E2.67419
G1 X10.618 Y13.839 E.00969
G1 X109.382 Y13.839 E2.67419
G1 X109.382 Y14.197 E.00969
G1 X10.618 Y14.197 E2.67419
G1 X10.618 Y14.554 E.00969
M73 P7 R2
G1 X109.382 Y14.554 E2.67419
G1 X109.382 Y14.912 E.00969
G1 X10.618 Y14.912 E2.67419
G1 X10.618 Y15.27 E.00969
G1 X109.382 Y15.27 E2.67419
G1 X109.382 Y15.628 E.00969
M73 P8 R2
G1 X10.618 Y15.628 E2.67419
G1 X10.618 Y15.986 E.00969
G1 X109.382 Y15.986 E2.67419
G1 X109.382 Y16.344 E.00969
M73 P9 R2
G1 X10.618 Y16.344 E2.67419
G1 X10.618 Y16.702 E.00969
G1 X109.382 Y16.702 E2.67419
G1 X109.382 Y17.059 E.00969
G1 X10.618 Y17.059 E2.67419
G1 X10.618 Y17.417 E.00969
M73 P10 R2
G1 X109.382 Y17.417 E2.67419
G1 X109.382 Y17.775 E.00969
G1 X10.618 Y17.775 E2.67419
G1 X10.618 Y18.133 E.00969
G1 X109.382 Y18.133 E2.67419
G1 X109.382 Y18.491 E.00969
M73 P11 R2
G1 X10.618 Y18.491 E2.67419
G1 X10.618 Y18.849 E.00969
G1 X109.382 Y18.849 E2.67419
G1 X109.382 Y19.206 E.00969
G1 X10.618 Y19.206 E2.67419
G1 X10.618 Y19.564 E.00969
M73 P12 R2
G1 X109.382 Y19.564 E2.67419
G1 X109.382 Y19.922 E.00969
G1 X10.618 Y19.922 E2.67419
G1 X10.618 Y20.28 E.00969
G1 X109.382 Y20.28 E2.67419
G1 X109.382 Y20.638 E.00969
M73 P13 R2
G1 X10.618 Y20.638 E2.67419
G1 X10.618 Y20.996 E.00969
G1 X109.382 Y20.996 E2.67419
G1 X109.382 Y21.353 E.00969
G1 X10.618 Y21.353 E2.67419
G1 X10.618 Y21.711 E.00969
M73 P14 R2
G1 X109.382 Y21.711 E2.67419
G1 X109.382 Y22.069 E.00969
G1 X10.618 Y22.069 E2.67419
G1 X10.618 Y22.427 E.00969
G1 X109.382 Y22.427 E2.67419
G1 X109.382 Y22.785 E.00969
M73 P15 R2
G1 X10.618 Y22.785 E2.67419
G1 X10.618 Y23.143 E.00969
G1 X109.382 Y23.143 E2.67419
G1 X109.382 Y23.5 E.00969
G1 X10.618 Y23.5 E2.67419
G1 X10.618 Y23.858 E.00969
M73 P16 R2
G1 X109.382 Y23.858 E2.67419
G1 X109.382 Y24.216 E.00969
G1 X10.618 Y24.216 E2.67419
G1 X10.618 Y24.574 E.00969
M73 P17 R1
G1 X109.382 Y24.574 E2.67419
G1 X109.382 Y24.932 E.00969
G1 X10.618 Y24.932 E2.67419
G1 X10.618 Y25.29 E.00969
G1 X109.382 Y25.29 E2.67419
G1 X109.382 Y25.647 E.00969
M73 P18 R1
G1 X10.618 Y25.647 E2.67419
G1 X10.618 Y26.005 E.00969
G1 X109.382 Y26.005 E2.67419
G1 X109.382 Y26.363 E.00969
G1 X10.618 Y26.363 E2.67419
G1 X10.618 Y26.721 E.00969
M73 P19 R1
G1 X109.382 Y26.721 E2.67419
G1 X109.382 Y27.079 E.00969
G1 X10.618 Y27.079 E2.67419
G1 X10.618 Y27.437 E.00969
G1 X109.382 Y27.437 E2.67419
G1 X109.382 Y27.795 E.00969
M73 P20 R1
G1 X10.618 Y27.795 E2.67419
G1 X10.618 Y28.152 E.00969
G1 X109.382 Y28.152 E2.67419
G1 X109.382 Y28.51 E.00969
G1 X10.618 Y28.51 E2.67419
G1 X10.618 Y28.868 E.00969
M73 P21 R1
G1 X109.382 Y28.868 E2.67419
G1 X109.382 Y29.226 E.00969
G1 X10.618 Y29.226 E2.67419
G1 X10.618 Y29.584 E.00969
G1 X109.382 Y29.584 E2.67419
G1 X109.382 Y29.942 E.00969
M73 P22 R1
G1 X10.618 Y29.942 E2.67419
G1 X10.618 Y30.299 E.00969
G1 X109.382 Y30.299 E2.67419
G1 X109.382 Y30.657 E.00969
G1 X10.618 Y30.657 E2.67419
G1 X10.618 Y31.015 E.00969
M73 P23 R1
G1 X109.382 Y31.015 E2.67419
G1 X109.382 Y31.373 E.00969
G1 X10.618 Y31.373 E2.67419
G1 X10.618 Y31.731 E.00969
G1 X109.382 Y31.731 E2.67419
M73 P24 R1
G1 X109.382 Y32.089 E.00969
G1 X10.618 Y32.089 E2.67419
G1 X10.618 Y32.446 E.00969
G1 X109.382 Y32.446 E2.67419
G1 X109.382 Y32.804 E.00969
M73 P25 R1
G1 X10.618 Y32.804 E2.67419
G1 X10.618 Y33.162 E.00969
G1 X109.382 Y33.162 E2.67419
G1 X109.382 Y33.52 E.00969
G1 X10.618 Y33.52 E2.67419
G1 X10.618 Y33.878 E.00969
M73 P26 R1
G1 X109.382 Y33.878 E2.67419
G1 X109.382 Y34.236 E.00969
G1 X10.618 Y34.236 E2.67419
G1 X10.618 Y34.593 E.00969
G1 X109.382 Y34.593 E2.67419
G1 X109.382 Y34.951 E.00969
M73 P27 R1
G1 X10.618 Y34.951 E2.67419
G1 X10.618 Y35.309 E.00969
G1 X109.382 Y35.309 E2.67419
G1 X109.382 Y35.667 E.00969
G1 X10.618 Y35.667 E2.67419
G1 X10.618 Y36.025 E.00969
M73 P28 R1
G1 X109.382 Y36.025 E2.67419
G1 X109.382 Y36.383 E.00969
G1 X10.618 Y36.383 E2.67419
G1 X10.618 Y36.74 E.00969
G1 X109.382 Y36.74 E2.67419
G1 X109.382 Y37.098 E.00969
M73 P29 R1
G1 X10.618 Y37.098 E2.67419
G1 X10.618 Y37.456 E.00969
G1 X109.382 Y37.456 E2.67419
G1 X109.382 Y37.814 E.00969
G1 X10.618 Y37.814 E2.67419
G1 X10.618 Y38.172 E.00969
M73 P30 R1
G1 X109.382 Y38.172 E2.67419
G1 X109.382 Y38.53 E.00969
G1 X10.618 Y38.53 E2.67419
G1 X10.618 Y38.888 E.00969
G1 X109.382 Y38.888 E2.67419
G1 X109.382 Y39.245 E.00969
M73 P31 R1
G1 X10.618 Y39.245 E2.67419
G1 X10.618 Y39.603 E.00969
G1 X109.382 Y39.603 E2.67419
G1 X109.382 Y39.961 E.00969
M73 P32 R1
G1 X10.618 Y39.961 E2.67419
G1 X10.618 Y40.319 E.00969
G1 X109.382 Y40.319 E2.67419
G1 X109.382 Y40.677 E.00969
G1 X10.618 Y40.677 E2.67419
G1 X10.618 Y41.035 E.00969
M73 P33 R1
G1 X109.382 Y41.035 E2.67419
G1 X109.382 Y41.392 E.00969
G1 X10.618 Y41.392 E2.67419
G1 X10.618 Y41.75 E.00969
G1 X109.382 Y41.75 E2.67419
G1 X109.382 Y42.108 E.00969
M73 P34 R1
G1 X10.618 Y42.108 E2.67419
G1 X10.618 Y42.466 E.00969
G1 X109.382 Y42.466 E2.67419
G1 X109.382 Y42.824 E.00969
G1 X10.618 Y42.824 E2.67419
G1 X10.618 Y43.182 E.00969
M73 P35 R1
G1 X109.382 Y43.182 E2.67419
G1 X109.382 Y43.539 E.00969
G1 X10.618 Y43.539 E2.67419
G1 X10.618 Y43.897 E.00969
G1 X109.382 Y43.897 E2.67419
G1 X109.382 Y44.255 E.00969
M73 P36 R1
G1 X10.618 Y44.255 E2.67419
G1 X10.618 Y44.613 E.00969
G1 X109.382 Y44.613 E2.67419
G1 X109.382 Y44.971 E.00969
G1 X10.618 Y44.971 E2.67419
G1 X10.618 Y45.329 E.00969
M73 P37 R1
G1 X109.382 Y45.329 E2.67419
G1 X109.382 Y45.686 E.00969
G1 X10.618 Y45.686 E2.67419
G1 X10.618 Y46.044 E.00969
G1 X109.382 Y46.044 E2.67419
G1 X109.382 Y46.402 E.00969
M73 P38 R1
G1 X10.618 Y46.402 E2.67419
G1 X10.618 Y46.76 E.00969
G1 X109.382 Y46.76 E2.67419
G1 X109.382 Y47.118 E.00969
G1 X10.618 Y47.118 E2.67419
G1 X10.618 Y47.476 E.00969
M73 P39 R1
G1 X109.382 Y47.476 E2.67419
G1 X109.382 Y47.833 E.00969
G1 X10.618 Y47.833 E2.67419
G1 X10.618 Y48.191 E.00969
M73 P40 R1
G1 X109.382 Y48.191 E2.67419
G1 X109.382 Y48.549 E.00969
G1 X10.618 Y48.549 E2.67419
G1 X10.618 Y48.907 E.00969
G1 X109.382 Y48.907 E2.67419
G1 X109.382 Y49.265 E.00969
M73 P41 R1
G1 X10.618 Y49.265 E2.67419
G1 X10.618 Y49.623 E.00969
G1 X109.382 Y49.623 E2.67419
G1 X109.382 Y49.981 E.00969
G1 X10.618 Y49.981 E2.67419
G1 X10.618 Y50.338 E.00969
M73 P42 R1
G1 X109.382 Y50.338 E2.67419
G1 X109.382 Y50.696 E.00969
G1 X10.618 Y50.696 E2.67419
G1 X10.618 Y51.054 E.00969
G1 X109.382 Y51.054 E2.67419
G1 X109.382 Y51.412 E.00969
M73 P43 R1
G1 X10.618 Y51.412 E2.67419
G1 X10.618 Y51.77 E.00969
G1 X109.382 Y51.77 E2.67419
G1 X109.382 Y52.128 E.00969
G1 X10.618 Y52.128 E2.67419
G1 X10.618 Y52.485 E.00969
M73 P44 R1
G1 X109.382 Y52.485 E2.67419
G1 X109.382 Y52.843 E.00969
G1 X10.618 Y52.843 E2.67419
G1 X10.618 Y53.201 E.00969
G1 X109.382 Y53.201 E2.67419
G1 X109.382 Y53.559 E.00969
M73 P45 R1
G1 X10.618 Y53.559 E2.67419
G1 X10.618 Y53.917 E.00969
G1 X109.382 Y53.917 E2.67419
G1 X109.382 Y54.275 E.00969
G1 X10.618 Y54.275 E2.67419
G1 X10.618 Y54.632 E.00969
M73 P46 R1
G1 X109.382 Y54.632 E2.67419
G1 X109.382 Y54.99 E.00969
G1 X10.618 Y54.99 E2.67419
G1 X10.618 Y55.348 E.00969
G1 X109.382 Y55.348 E2.67419
M73 P47 R1
G1 X109.382 Y55.706 E.00969
G1 X10.618 Y55.706 E2.67419
G1 X10.618 Y56.064 E.00969
G1 X109.382 Y56.064 E2.67419
G1 X109.382 Y56.422 E.00969
M73 P48 R1
G1 X10.618 Y56.422 E2.67419
G1 X10.618 Y56.779 E.00969
G1 X109.382 Y56.779 E2.67419
G1 X109.382 Y57.137 E.00969
G1 X10.618 Y57.137 E2.67419
G1 X10.618 Y57.495 E.00969
M73 P49 R1
G1 X109.382 Y57.495 E2.67419
G1 X109.382 Y57.853 E.00969
G1 X10.618 Y57.853 E2.67419
G1 X10.618 Y58.211 E.00969
G1 X109.382 Y58.211 E2.67419
G1 X109.382 Y58.569 E.00969
M73 P50 R1
G1 X10.618 Y58.569 E2.67419
G1 X10.618 Y58.927 E.00969
G1 X109.382 Y58.927 E2.67419
G1 X109.382 Y59.284 E.00969
G1 X10.618 Y59.284 E2.67419
G1 X10.618 Y59.642 E.00969
M73 P51 R1
G1 X109.382 Y59.642 E2.67419
G1 X109.382 Y60 E.00969
G1 X10.618 Y60 E2.67419
G1 X10.618 Y60.358 E.00969
G1 X109.382 Y60.358 E2.67419
G1 X109.382 Y60.716 E.00969
M73 P52 R1
G1 X10.618 Y60.716 E2.67419
G1 X10.618 Y61.074 E.00969
G1 X109.382 Y61.074 E2.67419
G1 X109.382 Y61.431 E.00969
G1 X10.618 Y61.431 E2.67419
G1 X10.618 Y61.789 E.00969
M73 P53 R1
G1 X109.382 Y61.789 E2.67419
G1 X109.382 Y62.147 E.00969
G1 X10.618 Y62.147 E2.67419
G1 X10.618 Y62.505 E.00969
G1 X109.382 Y62.505 E2.67419
G1 X109.382 Y62.863 E.00969
M73 P54 R1
G1 X10.618 Y62.863 E2.67419
G1 X10.618 Y63.221 E.00969
G1 X109.382 Y63.221 E2.67419
G1 X109.382 Y63.578 E.00969
M73 P55 R1
G1 X10.618 Y63.578 E2.67419
G1 X10.618 Y63.936 E.00969
G1 X109.382 Y63.936 E2.67419
G1 X109.382 Y64.294 E.00969
G1 X10.618 Y64.294 E2.67419
G1 X10.618 Y64.652 E.00969
M73 P56 R1
G1 X109.382 Y64.652 E2.67419
G1 X109.382 Y65.01 E.00969
G1 X10.618 Y65.01 E2.67419
G1 X10.618 Y65.368 E.00969
G1 X109.382 Y65.368 E2.67419
G1 X109.382 Y65.725 E.00969
M73 P57 R1
G1 X10.618 Y65.725 E2.67419
G1 X10.618 Y66.083 E.00969
G1 X109.382 Y66.083 E2.67419
G1 X109.382 Y66.441 E.00969
G1 X10.618 Y66.441 E2.67419
G1 X10.618 Y66.799 E.00969
M73 P58 R1
G1 X109.382 Y66.799 E2.67419
G1 X109.382 Y67.157 E.00969
G1 X10.618 Y67.157 E2.67419
G1 X10.618 Y67.515 E.00969
M73 P58 R0
G1 X109.382 Y67.515 E2.67419
G1 X109.382 Y67.872 E.00969
M73 P59 R0
G1 X10.618 Y67.872 E2.67419
G1 X10.618 Y68.23 E.00969
G1 X109.382 Y68.23 E2.67419
G1 X109.382 Y68.588 E.00969
G1 X10.618 Y68.588 E2.67419
G1 X10.618 Y68.946 E.00969
M73 P60 R0
G1 X109.382 Y68.946 E2.67419
G1 X109.382 Y69.304 E.00969
G1 X10.618 Y69.304 E2.67419
G1 X10.618 Y69.662 E.00969
G1 X109.382 Y69.662 E2.67419
G1 X109.382 Y70.02 E.00969
M73 P61 R0
G1 X10.618 Y70.02 E2.67419
G1 X10.618 Y70.377 E.00969
G1 X109.382 Y70.377 E2.67419
G1 X109.382 Y70.735 E.00969
G1 X10.618 Y70.735 E2.67419
G1 X10.618 Y71.093 E.00969
M73 P62 R0
G1 X109.382 Y71.093 E2.67419
G1 X109.382 Y71.451 E.00969
G1 X10.618 Y71.451 E2.67419
G1 X10.618 Y71.809 E.00969
M73 P63 R0
G1 X109.382 Y71.809 E2.67419
G1 X109.382 Y72.167 E.00969
G1 X10.618 Y72.167 E2.67419
G1 X10.618 Y72.524 E.00969
G1 X109.382 Y72.524 E2.67419
G1 X109.382 Y72.882 E.00969
M73 P64 R0
G1 X10.618 Y72.882 E2.67419
G1 X10.618 Y73.24 E.00969
G1 X109.382 Y73.24 E2.67419
G1 X109.382 Y73.598 E.00969
G1 X10.618 Y73.598 E2.67419
G1 X10.618 Y73.956 E.00969
M73 P65 R0
G1 X109.382 Y73.956 E2.67419
G1 X109.382 Y74.314 E.00969
G1 X10.618 Y74.314 E2.67419
G1 X10.618 Y74.671 E.00969
G1 X109.382 Y74.671 E2.67419
G1 X109.382 Y75.029 E.00969
M73 P66 R0
G1 X10.618 Y75.029 E2.67419
G1 X10.618 Y75.387 E.00969
G1 X109.382 Y75.387 E2.67419
G1 X109.382 Y75.745 E.00969
G1 X10.618 Y75.745 E2.67419
G1 X10.618 Y76.103 E.00969
M73 P67 R0
G1 X109.382 Y76.103 E2.67419
G1 X109.382 Y76.461 E.00969
G1 X10.618 Y76.461 E2.67419
G1 X10.618 Y76.818 E.00969
G1 X109.382 Y76.818 E2.67419
G1 X109.382 Y77.176 E.00969
M73 P68 R0
G1 X10.618 Y77.176 E2.67419
G1 X10.618 Y77.534 E.00969
G1 X109.382 Y77.534 E2.67419
G1 X109.382 Y77.892 E.00969
G1 X10.618 Y77.892 E2.67419
G1 X10.618 Y78.25 E.00969
M73 P69 R0
G1 X109.382 Y78.25 E2.67419
G1 X109.382 Y78.608 E.00969
G1 X10.618 Y78.608 E2.67419
G1 X10.618 Y78.965 E.00969
G1 X109.382 Y78.965 E2.67419
M73 P70 R0
G1 X109.382 Y79.323 E.00969
G1 X10.618 Y79.323 E2.67419
G1 X10.618 Y79.681 E.00969
G1 X109.382 Y79.681 E2.67419
G1 X109.382 Y80.039 E.00969
M73 P71 R0
G1 X10.618 Y80.039 E2.67419
G1 X10.618 Y80.397 E.00969
G1 X109.382 Y80.397 E2.67419
G1 X109.382 Y80.755 E.00969
G1 X10.618 Y80.755 E2.67419
G1 X10.618 Y81.113 E.00969
M73 P72 R0
G1 X109.382 Y81.113 E2.67419
G1 X109.382 Y81.47 E.00969
G1 X10.618 Y81.47 E2.67419
G1 X10.618 Y81.828 E.00969
G1 X109.382 Y81.828 E2.67419
G1 X109.382 Y82.186 E.00969
M73 P73 R0
G1 X10.618 Y82.186 E2.67419
G1 X10.618 Y82.544 E.00969
G1 X109.382 Y82.544 E2.67419
G1 X109.382 Y82.902 E.00969
G1 X10.618 Y82.902 E2.67419
G1 X10.618 Y83.26 E.00969
M73 P74 R0
G1 X109.382 Y83.26 E2.67419
G1 X109.382 Y83.617 E.00969
G1 X10.618 Y83.617 E2.67419
G1 X10.618 Y83.975 E.00969
G1 X109.382 Y83.975 E2.67419
G1 X109.382 Y84.333 E.00969
M73 P75 R0
G1 X10.618 Y84.333 E2.67419
G1 X10.618 Y84.691 E.00969
G1 X109.382 Y84.691 E2.67419
G1 X109.382 Y85.049 E.00969
G1 X10.618 Y85.049 E2.67419
G1 X10.618 Y85.407 E.00969
M73 P76 R0
G1 X109.382 Y85.407 E2.67419
G1 X109.382 Y85.764 E.00969
G1 X10.618 Y85.764 E2.67419
G1 X10.618 Y86.122 E.00969
G1 X109.382 Y86.122 E2.67419
G1 X109.382 Y86.48 E.00969
M73 P77 R0
G1 X10.618 Y86.48 E2.67419
G1 X10.618 Y86.838 E.00969
G1 X109.382 Y86.838 E2.67419
G1 X109.382 Y87.196 E.00969
M73 P78 R0
G1 X10.618 Y87.196 E2.67419
G1 X10.618 Y87.554 E.00969
G1 X109.382 Y87.554 E2.67419
G1 X109.382 Y87.911 E.00969
G1 X10.618 Y87.911 E2.67419
G1 X10.618 Y88.269 E.00969
M73 P79 R0
G1 X109.382 Y88.269 E2.67419
G1 X109.382 Y88.627 E.00969
G1 X10.618 Y88.627 E2.67419
G1 X10.618 Y88.985 E.00969
G1 X109.382 Y88.985 E2.67419
G1 X109.382 Y89.343 E.00969
M73 P80 R0
G1 X10.618 Y89.343 E2.67419
G1 X10.618 Y89.701 E.00969
G1 X109.382 Y89.701 E2.67419
G1 X109.382 Y90.059 E.00969
G1 X10.618 Y90.058 E2.67419
G1 X10.618 Y90.416 E.00969
M73 P81 R0
G1 X109.382 Y90.416 E2.67419
G1 X109.382 Y90.774 E.00969
G1 X10.618 Y90.774 E2.67419
G1 X10.618 Y91.132 E.00969
G1 X109.382 Y91.132 E2.67419
G1 X109.382 Y91.49 E.00969
M73 P82 R0
G1 X10.618 Y91.49 E2.67419
G1 X10.618 Y91.848 E.00969
G1 X109.382 Y91.848 E2.67419
G1 X109.382 Y92.206 E.00969
G1 X10.618 Y92.206 E2.67419
G1 X10.618 Y92.563 E.00969
M73 P83 R0
G1 X109.382 Y92.563 E2.67419
G1 X109.382 Y92.921 E.00969
G1 X10.618 Y92.921 E2.67419
G1 X10.618 Y93.279 E.00969
G1 X109.382 Y93.279 E2.67419
G1 X109.382 Y93.637 E.00969
M73 P84 R0
G1 X10.618 Y93.637 E2.67419
G1 X10.618 Y93.995 E.00969
G1 X109.382 Y93.995 E2.67419
G1 X109.382 Y94.353 E.00969
G1 X10.618 Y94.353 E2.67419
G1 X10.618 Y94.71 E.00969
M73 P85 R0
G1 X109.382 Y94.71 E2.67419
G1 X109.382 Y95.068 E.00969
G1 X10.618 Y95.068 E2.67419
G1 X10.618 Y95.426 E.00969
M73 P86 R0
G1 X109.382 Y95.426 E2.67419
G1 X109.382 Y95.784 E.00969
G1 X10.618 Y95.784 E2.67419
G1 X10.618 Y96.142 E.00969
G1 X109.382 Y96.142 E2.67419
G1 X109.382 Y96.5 E.00969
M73 P87 R0
G1 X10.618 Y96.5 E2.67419
G1 X10.618 Y96.857 E.00969
G1 X109.382 Y96.857 E2.67419
G1 X109.382 Y97.215 E.00969
G1 X10.618 Y97.215 E2.67419
G1 X10.618 Y97.573 E.00969
M73 P88 R0
G1 X109.382 Y97.573 E2.67419
G1 X109.382 Y97.931 E.00969
G1 X10.618 Y97.931 E2.67419
G1 X10.618 Y98.289 E.00969
G1 X109.382 Y98.289 E2.67419
G1 X109.382 Y98.647 E.00969
M73 P89 R0
G1 X10.618 Y98.647 E2.67419
G1 X10.618 Y99.004 E.00969
G1 X109.382 Y99.004 E2.67419
G1 X109.382 Y99.362 E.00969
G1 X10.618 Y99.362 E2.67419
G1 X10.618 Y99.72 E.00969
M73 P90 R0
G1 X109.382 Y99.72 E2.67419
G1 X109.382 Y100.078 E.00969
G1 X10.618 Y100.078 E2.67419
G1 X10.618 Y100.436 E.00969
G1 X109.382 Y100.436 E2.67419
G1 X109.382 Y100.794 E.00969
M73 P91 R0
G1 X10.618 Y100.794 E2.67419
G1 X10.618 Y101.152 E.00969
G1 X109.382 Y101.152 E2.67419
G1 X109.382 Y101.509 E.00969
G1 X10.618 Y101.509 E2.67419
G1 X10.618 Y101.867 E.00969
M73 P92 R0
G1 X109.382 Y101.867 E2.67419
G1 X109.382 Y102.225 E.00969
G1 X10.618 Y102.225 E2.67419
G1 X10.618 Y102.583 E.00969
G1 X109.382 Y102.583 E2.67419
M73 P93 R0
G1 X109.382 Y102.941 E.00969
G1 X10.618 Y102.941 E2.67419
G1 X10.618 Y103.299 E.00969
G1 X109.382 Y103.299 E2.67419
G1 X109.382 Y103.656 E.00969
M73 P94 R0
G1 X10.618 Y103.656 E2.67419
G1 X10.618 Y104.014 E.00969
G1 X109.382 Y104.014 E2.67419
G1 X109.382 Y104.372 E.00969
G1 X10.618 Y104.372 E2.67419
G1 X10.618 Y104.73 E.00969
M73 P95 R0
G1 X109.382 Y104.73 E2.67419
G1 X109.382 Y105.088 E.00969
G1 X10.618 Y105.088 E2.67419
G1 X10.618 Y105.446 E.00969
G1 X109.382 Y105.446 E2.67419
G1 X109.382 Y105.803 E.00969
M73 P96 R0
G1 X10.618 Y105.803 E2.67419
G1 X10.618 Y106.161 E.00969
G1 X109.382 Y106.161 E2.67419
G1 X109.382 Y106.519 E.00969
G1 X10.618 Y106.519 E2.67419
G1 X10.618 Y106.877 E.00969
M73 P97 R0
G1 X109.382 Y106.877 E2.67419
G1 X109.382 Y107.235 E.00969
G1 X10.618 Y107.235 E2.67419
G1 X10.618 Y107.593 E.00969
G1 X109.382 Y107.593 E2.67419
G1 X109.382 Y107.95 E.00969
M73 P98 R0
G1 X10.618 Y107.95 E2.67419
G1 X10.618 Y108.308 E.00969
G1 X109.382 Y108.308 E2.67419
G1 X109.382 Y108.666 E.00969
G1 X10.618 Y108.666 E2.67419
G1 X10.618 Y109.024 E.00969
M73 P99 R0
G1 X109.382 Y109.024 E2.67419
G1 X109.382 Y109.382 E.00969
G1 X10.457 Y109.382 E2.67854
; stop printing object z-offset-check.stl id:15 copy 0
EXCLUDE_OBJECT_END NAME=z_offset_check_stl_id_15_copy_0
G1 E-.65714 F1800
;WIPE_START
G1 F12600
G1 X11.457 Y109.382 E-.14286
;WIPE_END
M106 S0
;TYPE:Custom
; filament end gcode
PRINT_END
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 754.16
; filament used [cm3] = 1.81
; filament used [g] = 1.89
; filament cost = 0.04
; total filament used [g] = 1.89
; total filament cost = 0.04
; total layers count = 1
; estimated printing time (normal mode) = 2m 23s
; estimated first layer printing time (normal mode) = 0.504875s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 100%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 0
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 5
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 100
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 3
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 0
; cool_plate_temp_initial_layer = 0
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 20000
; default_bed_type = 
; default_filament_colour = #101010
; default_filament_profile = "Generic PLA @System"
; default_jerk = 9
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @Voron
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = accel_to_decel_factor;bottom_shell_layers;bridge_speed;default_acceleration;default_jerk;enable_overhang_speed;gap_infill_speed;initial_layer_acceleration;initial_layer_infill_speed;initial_layer_speed;inner_wall_acceleration;inner_wall_speed;internal_solid_infill_speed;outer_wall_acceleration;outer_wall_speed;sparse_infill_density;sparse_infill_pattern;sparse_infill_speed;top_surface_acceleration;top_surface_speed;travel_acceleration;travel_speed;wall_loops;default_filament_colour;enable_pressure_advance;fan_cooling_layer_time;fan_max_speed;fan_min_speed;filament_flow_ratio;filament_max_volumetric_speed;filament_vendor;hot_plate_temp;internal_bridge_fan_speed;nozzle_temperature;nozzle_temperature_initial_layer;overhang_fan_speed;overhang_fan_threshold;pressure_advance;reduce_fan_stop_start_freq;slow_down_for_layer_cooling;slow_down_layer_time;support_material_interface_fan_speed;machine_start_gcode;print_host
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 0
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 100
; eng_plate_temp_initial_layer = 105
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #101010
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 5
; fan_kickstart = 0
; fan_max_speed = 30
; fan_min_speed = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #101010
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.04
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_flow_ratio = 0.91
; filament_ids = OGFB99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 25
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Sunlu ABS black"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; Filament gcode\n"
; filament_toolchange_delay = 0
; filament_type = ABS
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Sunlu
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 500
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 102
; hot_plate_temp_initial_layer = 105
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 15%
; inherits_group = "process template @Voron Voron 0.1 0.4 nozzle";"Generic ABS @System";"Voron Voron 0.1 0.4 nozzle"
; initial_layer_acceleration = 10000
; initial_layer_infill_speed = 210
; initial_layer_jerk = 9
; initial_layer_line_width = 0.4
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 100
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 15000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.4
; inner_wall_speed = 600
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = 0
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.4
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 500
; ironing_angle = -1
; ironing_fan_speed = -1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 0.4
; long_retractions_when_cut = 0
; machine_end_gcode = PRINT_END
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 12,12
; machine_max_jerk_y = 12,12
; machine_max_jerk_z = 0.2,0.4
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 25,25
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 12,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = PRINT_START EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]\n
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.1
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 250
; nozzle_temperature_initial_layer = 255
; nozzle_temperature_range_high = 280
; nozzle_temperature_range_low = 240
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 10000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.4
; outer_wall_speed = 400
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 25
; overhang_fan_threshold = 75%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.04
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Voron Voron 0.1 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 2xspeed strong @Voron Voron 0.1 0.4 nozzle
; printable_area = 0x0,120x0,120x120,0x120
; printable_height = 120
; printer_model = Voron Voron 0.1
; printer_notes = 
; printer_settings_id = Formbot V0.2 0.4 nozzle
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 0
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 0
; slow_down_layer_time = 0.5
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 0,90
; sparse_infill_acceleration = 100%
; sparse_infill_density = 40%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.4
; sparse_infill_pattern = gyroid
; sparse_infill_rotate_template = 
; sparse_infill_speed = 540
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 0
; supertack_plate_temp_initial_layer = 0
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0.4
; support_material_interface_fan_speed = 100
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 110
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 100
; textured_plate_temp_initial_layer = 105
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG, 300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 0.6
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 10000
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 0.4
; top_surface_pattern = monotonicline
; top_surface_speed = 400
; travel_acceleration = 20000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 600
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 4
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 56.000
; wipe_tower_x = 56,81,165
; wipe_tower_y = 5.771
; wipe_tower_y = 5.77143,116,250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 105
; bed_shape = 0x0,120x0,120x120,0x120
; first_layer_temperature = 255
; first_layer_height = 0.200
; CONFIG_BLOCK_END


